set( proj SuperElastix )
#TODO either of these variables should contain the MSVC specific compilerflags
MESSAGE( STATUS "proj SuperElastix MSVC Compiler flags: " ${MSVC_COMP_FLAGS} )
MESSAGE( STATUS "proj SuperElastix CompilerConfigurations: " ${CompilerConfigurations} )

ExternalProject_Add( ${proj}
  DOWNLOAD_COMMAND ""
  SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/..
  BINARY_DIR ${proj}-build
  CMAKE_ARGS
    --no-warn-unused-cli
	# TODO make flags MSVC specific
    -DCMAKE_CXX_FLAGS:STRING=/MP
    -DCMAKE_C_FLAGS:STRING=/MP
    -DSUPERELASTIX_BUILD_EXAMPLES:BOOL=${SUPERELASTIX_BUILD_EXAMPLES}
    -DSUPERELASTIX_BUILD_TESTING:BOOL=${SUPERELASTIX_BUILD_TESTING}
    -DSUPERELASTIX_BUILD_LONG_TESTS:BOOL=${SUPERELASTIX_BUILD_LONG_TESTS}
    -DSUPERELASTIX_BUILD_BENCHMARKING:BOOL=${SUPERELASTIX_BUILD_BENCHMARKING}
    -DSUPERELASTIX_BUILD_DASHBOARD:BOOL=${SUPERELASTIX_BUILD_DASHBOARD}
    -DITK_DIR:PATH=${ITK_DIR}
    -DBOOST_ROOT:PATH=${BOOST_ROOT}
    -DGTEST_ROOT:PATH=${GTEST_ROOT}
    -DELASTIX_USE_FILE:PATH=${ELASTIX_USE_FILE}
  DEPENDS ${ELASTIX_DEPENDENCIES}
  INSTALL_COMMAND ""
)
